books/urls.py
from django.urls import path

from . import views
app_name = 'books'

urlpatterns = [
    path('get_books', views.BooksListRetrieveAPiView.as_view(), name='get_books'),
]

bookstore_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.UserLogin.as_view(), name='login'),
    path('logout', views.user_logout, name='logout')
]

books/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render
from rest_framework import views
import pandas as pd
# Create your views here.
from rest_framework.permissions import IsAuthenticated


class BooksListRetrieveAPiView(views.APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        rows = request.GET.get('q', None)
        df = pd.read_csv('static/books.csv')
        df = df.fillna('')
        if rows:
            row_data = df.loc[:rows]
            value = row_data.to_dict(orient='records')
        else:
            value = df.to_dict(orient='records')

        return render(request, 'books/index.html', {'books': value})

users/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, HttpResponseRedirect, redirect
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib import messages

from users.serializers import LoginSerializer


class UserLogin(APIView):

    def get(self, request):
        return render(request, 'users/login.html')

    def post(self, request):
        try:
            serializer = LoginSerializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            user = serializer.save()
            login(request, user)
            messages.success(request, 'login successful')
            return redirect('books:get_books')
        except Exception as e:
            messages.error(request, str(e))
            return HttpResponseRedirect('login')


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def user_logout(request):
    logout(request)
    return Response('User Logged out successfully')

templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Book Management</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Book Management</a>
        <form class="form-inline" action="{% url 'books:get_books' %}">
            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Enter Rows No" 
            aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      </nav>
    <div class="container">
            <table class="table table-striped table-bordered table-responsive" style="table-layout: fixed;word-wrap: break-word;">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Authors</th>
                        <th scope="col">Isbn13</th>
                        <th scope="col">Isbn10</th>
                        <th scope="col">Price</th>
                        <th scope="col">Publisher</th>
                        <th scope="col">Pubyear</th>
                        <th scope="col">Subjects</th>
                        <th scope="col">Lexile</th>
                        <th scope="col">Pages</th>
                        <th scope="col">Dimensions</th>
                    </tr>
                </thead>
                <tbody>
                {% for each in books %}
                <tr>
                    <td >{{ each.id }}</td>
                    <td>{{ each.title }}</td>
                    <td>{{ each.author }}</td>
                    <td >{{ each.authors }}</td>
                    <td>{{ each.isbn13 }}</td>
                    <td>{{ each.isbn10 }}</td>
                    <td>{{ each.price }}</td>
                    <td>{{ each.publisher }}</td>
                    <td>{{ each.pubyear }}</td>
                    <td colspan="2">{{ each.subjects }}</td>
                    <td>{{ each.lexile }}</td>
                    <td>{{ each.pages }}</td>
                    <td>{{ each.dimensions }}</td>
                </tr>
            </tbody>
            {% endfor %}
            </table>
        </div>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Login</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="#">Book Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books:get_books' %}">Main</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                </ul>
    
            </div>
    
        </div>
    </nav>
    <main class="login-form">
        <div class="cotainer">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Login</div>
                        <div class="card-body">
                            <form method="POST" action="{% url 'users:login' %}"> {% csrf_token %}
                                {% if messages %}
                                <div class="bs-example">
                                    <div class="wd-350 alert alert-danger" >
                                        {% for message in messages %}
                                          <strong > {{ message }} </strong>
                                        {% endfor %}
                                    </div>
                                </div>
                                {% endif %}
                                <div class="form-group row">
                                    <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>
                                    <div class="col-md-6">
                                        <input type="text" id="email_address" class="form-control" name="email" required autofocus>
                                    </div>
                                </div>
    
                                <div class="form-group row">
                                    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                    <div class="col-md-6">
                                        <input type="password" id="password" class="form-control" name="password" required>
                                    </div>
                                </div>
    
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Login
                                    </button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
    
    </main>
    
</body>
</html>